import React, { useState } from "react";
import { Coins, Sparkles, RefreshCw, Star, Trophy, AlertTriangle } from "lucide-react";

interface JiliSlotsProps {
  userBalance: number;
  phoneNumber: string;
  updateProfile: (phone: string) => void;
  setNotification: (msg: string | null) => void;
}

const SYMBOLS = [
  { char: "🐯", name: "Tiger", value: 10, payout: 25, color: "from-amber-500 to-yellow-600" }, // Wild
  { char: "👑", name: "Crown", value: 5, payout: 15, color: "from-yellow-400 to-amber-500" },
  { char: "💎", name: "Diamond", value: 3, payout: 8, color: "from-cyan-400 to-blue-500" },
  { char: "🔥", name: "Seven", value: 2, payout: 5, color: "from-red-500 to-orange-500" },
  { char: "🍒", name: "Cherry", value: 1, payout: 3, color: "from-rose-500 to-red-600" },
  { char: "🪙", name: "Coin", value: 0.5, payout: 1.5, color: "from-yellow-500 to-yellow-300" }
];

export function JiliSlots({ userBalance, phoneNumber, updateProfile, setNotification }: JiliSlotsProps) {
  const [spinning, setSpinning] = useState(false);
  const [betAmt, setBetAmt] = useState<number>(50);
  const [reels, setReels] = useState<string[][]>([
    ["👑", "💎", "🍒"],
    ["🐯", "👑", "🔥"],
    ["💎", "🍒", "🪙"]
  ]);
  const [lastWinAmt, setLastWinAmt] = useState<number>(0);
  const [winMessage, setWinMessage] = useState<string | null>(null);

  const startSpin = async () => {
    if (!phoneNumber) {
      setNotification("Please authenticate/login to spin with real credits!");
      return;
    }
    if (userBalance < betAmt) {
      setNotification("Insufficient credits. Please recharge your wallet!");
      return;
    }
    if (spinning) return;

    setSpinning(true);
    setWinMessage(null);
    setLastWinAmt(0);

    // Dynamic rotation intervals simulation
    let counter = 0;
    const interval = setInterval(() => {
      setReels(() => [
        Array.from({ length: 3 }, () => SYMBOLS[Math.floor(Math.random() * SYMBOLS.length)].char),
        Array.from({ length: 3 }, () => SYMBOLS[Math.floor(Math.random() * SYMBOLS.length)].char),
        Array.from({ length: 3 }, () => SYMBOLS[Math.floor(Math.random() * SYMBOLS.length)].char)
      ]);
      counter++;
      if (counter > 12) {
        clearInterval(interval);
        finalizeSlotSpin();
      }
    }, 100);
  };

  const finalizeSlotSpin = async () => {
    try {
      // Connect to unified backend
      const res = await (await fetch("/api/games/slot/spin", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ phone: phoneNumber, amount: betAmt })
      })).json();

      if (res.success) {
        // Build final reel result that conforms to the profit status generated by backend
        const chosenReels = determineReelsFromMultiplier(res.multiplier);
        setReels(chosenReels);
        
        setLastWinAmt(res.winAmount);
        if (res.winAmount > 0) {
          setWinMessage(`🎉 Jackpot Multiplier ${res.multiplier}x! Won ₹${res.winAmount.toFixed(2)} credits!`);
          setNotification(`🎰 Jili Slot payout: ₹${res.winAmount.toFixed(2)} won!`);
        } else {
          setWinMessage("Try Again! Next spin might hit the Golden Tiger.");
        }
        updateProfile(phoneNumber);
      } else {
        setNotification(res.error || "System slot connection error");
      }
    } catch (e) {
      console.error(e);
    } finally {
      setSpinning(false);
    }
  };

  // Helper to align slots symbols display to background multiplier result beautifully
  const determineReelsFromMultiplier = (mult: number): string[][] => {
    if (mult === 20) {
      // Tiger Jackpot match
      return [["🐯", "🐯", "🐯"], ["💎", "👑", "🔥"], ["🍒", "🪙", "🍒"]];
    } else if (mult === 5) {
      // Crown Mega match
      return [["👑", "👑", "👑"], ["🐯", "🍒", "🔥"], ["💎", "🪙", "💎"]];
    } else if (mult === 2) {
      // Diamond win row
      return [["💎", "💎", "💎"], ["🍒", "🪙", "🔥"], ["🐯", "👑", "🍒"]];
    } else if (mult === 0.5) {
      // Coin mini pay row
      return [["🪙", "🪙", "🪙"], ["🐯", "👑", "💎"], ["🍒", "🔥", "🍒"]];
    } else {
      // No straight match row
      return [
        ["💎", "👑", "🍒"],
        ["🍒", "🪙", "🔥"],
        ["🐯", "💎", "🪙"]
      ];
    }
  };

  return (
    <div className="bg-zinc-900/90 border border-zinc-800 rounded-3xl p-5 space-y-6 shadow-2xl relative overflow-hidden">
      {/* Absolute aura gold light back */}
      <div className="absolute top-0 right-0 w-36 h-36 bg-amber-500/10 rounded-full blur-3xl pointer-events-none"></div>

      {/* Header section */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 border-b border-zinc-800 pb-3">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center">
            <Sparkles className="w-5 h-5 text-amber-400 animate-spin" strokeWidth={2.5} />
          </div>
          <div>
            <h3 className="font-extrabold text-lg text-white tracking-tight flex items-center gap-1.5 uppercase">
              <span>Jili Fortune Slot</span>
              <span className="text-[10px] bg-amber-500 text-zinc-950 font-black px-1.5 py-0.5 rounded tracking-widest leading-none">VIP</span>
            </h3>
            <p className="text-xs text-zinc-400">Match active 🐯 Wild Tigers or 👑 Crowns to trigger 25x multipliers instantly.</p>
          </div>
        </div>
      </div>

      {/* Main slot physical box overlay */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
        
        {/* Left Side: Reels Board */}
        <div className="md:col-span-2 bg-gradient-to-b from-zinc-950 to-zinc-900 rounded-2xl p-5 border-4 border-amber-500/30 shadow-inner flex flex-col justify-center gap-4 min-h-[220px]">
          
          <div className="grid grid-cols-3 gap-3 self-center max-w-sm w-full">
            {reels.map((col, colIdx) => (
              <div 
                key={colIdx} 
                className={`bg-zinc-950/80 border-2 border-zinc-805/60 rounded-xl p-4 flex flex-col items-center justify-center gap-3 relative overflow-hidden ${
                  spinning ? 'animate-pulse scale-98 brightness-110 border-amber-500/30' : ''
                }`}
              >
                {col.map((sym, symIdx) => {
                  const symConfig = SYMBOLS.find(s => s.char === sym);
                  return (
                    <div 
                      key={symIdx} 
                      className={`text-3xl filter drop-shadow-[0_2px_4px_rgba(0,0,0,0.5)] transform hover:scale-115 transition-transform duration-200 ${
                        spinning ? 'translate-y-1 animate-bounce opacity-80' : ''
                      }`}
                    >
                      {sym}
                    </div>
                  );
                })}
              </div>
            ))}
          </div>

          {/* Dynamic reel lighting indicator */}
          <div className="text-center font-mono text-[10px] text-zinc-500 tracking-wider">
            {spinning ? "🔥 WHEELS ROTATING..." : "🔴 STABLE READY FOR ROUND"}
          </div>
        </div>

        {/* Right Side: Symbol value index cards */}
        <div className="md:col-span-1 space-y-4">
          <div className="bg-zinc-950 rounded-2xl border border-zinc-850 p-4 space-y-3">
            <h4 className="text-[11px] font-black text-zinc-400 uppercase tracking-widest flex items-center gap-1">
              <Star className="w-3.5 h-3.5 text-amber-500" /> Multiplier Paytable
            </h4>
            
            <div className="grid grid-cols-2 gap-2 text-[10px] font-mono">
              {SYMBOLS.map((s, idx) => (
                <div key={idx} className="flex items-center justify-between py-1 border-b border-zinc-900">
                  <span className="text-sm">{s.char}</span>
                  <span className="text-zinc-400">{s.name}</span>
                  <span className="text-amber-400 font-bold">{s.payout}x</span>
                </div>
              ))}
            </div>
          </div>

          {/* Bet sizes and actions */}
          <div className="space-y-3">
            <div className="flex justify-between items-center text-xs">
              <span className="text-zinc-500 font-bold uppercase tracking-wide">Stake Limit:</span>
              <div className="flex gap-1.5">
                {[50, 200, 500, 1000].map(v => (
                  <button 
                    key={v}
                    disabled={spinning}
                    onClick={() => setBetAmt(v)}
                    className={`px-2.5 py-1 text-[10px] font-bold font-mono rounded cursor-pointer ${
                      betAmt === v 
                        ? 'bg-amber-500 text-zinc-950 font-bold' 
                        : 'bg-zinc-850 hover:bg-zinc-800 text-zinc-400'
                    }`}
                  >
                    ₹{v}
                  </button>
                ))}
              </div>
            </div>

            <button
              onClick={startSpin}
              disabled={spinning}
              className={`w-full bg-gradient-to-r from-amber-500 to-yellow-400 hover:from-amber-400 hover:to-yellow-300 text-zinc-950 font-black text-sm py-4 rounded-xl flex items-center justify-center space-x-2 shadow-lg shadow-amber-500/10 cursor-pointer ${
                spinning ? 'opacity-40 cursor-not-allowed' : 'active:scale-95'
              }`}
            >
              <RefreshCw className={`w-4 h-4 ${spinning ? 'animate-spin text-zinc-950' : 'text-zinc-950'}`} />
              <span className="uppercase tracking-widest">SPIN SLOT REEL</span>
            </button>
          </div>
        </div>
      </div>

      {/* Win Banner notification */}
      {winMessage && (
        <div className={`p-3.5 rounded-2xl border text-xs text-center font-bold flex items-center justify-center gap-2 animate-bounce ${
          lastWinAmt > 0 
            ? 'bg-emerald-950/40 border-emerald-900/50 text-emerald-300' 
            : 'bg-zinc-950 border-zinc-850 text-zinc-400'
        }`}>
          <span>{winMessage}</span>
        </div>
      )}
    </div>
  );
}
